### ISSUE TITLE
Network error 

### ISSUE THREAD

**Issue by flaryx32** [RacoonDog/MeteorServerSeeker#6]
pressing get players causes network error to be dsiplayed, logs:

```

[17:19:35] [Meteor-Executor-4/ERROR]: Could not post to 'server_info': 
java.io.IOException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:966) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133) ~[java.net.http:?]
	at knot/meteordevelopment.meteorclient.utils.network.Http$Request._sendResponse(Http.java:118) ~[meteor-client-0.5.9.jar:?]
	at knot/meteordevelopment.meteorclient.utils.network.Http$Request._send(Http.java:127) ~[meteor-client-0.5.9.jar:?]
	at knot/meteordevelopment.meteorclient.utils.network.Http$Request.sendJson(Http.java:168) ~[meteor-client-0.5.9.jar:?]
	at knot/de.damcraft.serverseeker.gui.GetInfoScreen.lambda$initWidgets$2(GetInfoScreen.java:79) ~[server-seeker-4.5.2.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1107) ~[gson-2.10.1.jar:?]
	at knot/meteordevelopment.meteorclient.utils.network.JsonBodyHandler.lambda$getBody$1(JsonBodyHandler.java:26) ~[meteor-client-0.5.9.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(CompletableFuture.java:2948) ~[?:?]
	at knot/meteordevelopment.meteorclient.utils.network.JsonBodyHandler.getBody(JsonBodyHandler.java:26) ~[meteor-client-0.5.9.jar:?]
	at java.net.http/jdk.internal.net.http.common.HttpBodySubscriberWrapper.getBody(HttpBodySubscriberWrapper.java:360) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.ResponseSubscribers.lambda$getBodyAsync$3(ResponseSubscribers.java:1175) ~[java.net.http:?]
	... 3 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at knot/com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
	at knot/com.google.gson.Gson.fromJson(Gson.java:1107) ~[gson-2.10.1.jar:?]
	at knot/meteordevelopment.meteorclient.utils.network.JsonBodyHandler.lambda$getBody$1(JsonBodyHandler.java:26) ~[meteor-client-0.5.9.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(CompletableFuture.java:2948) ~[?:?]
	at knot/meteordevelopment.meteorclient.utils.network.JsonBodyHandler.getBody(JsonBodyHandler.java:26) ~[meteor-client-0.5.9.jar:?]
	at java.net.http/jdk.internal.net.http.common.HttpBodySubscriberWrapper.getBody(HttpBodySubscriberWrapper.java:360) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.ResponseSubscribers.lambda$getBodyAsync$3(ResponseSubscribers.java:1175) ~[java.net.http:?]
	... 3 more
```

**Comment by flaryx32** [comment]
ah looking into this it's jsut the serverseeker api server being down for some reason :( sooo yeah :(

**Comment by Broshan1337** [comment]
gg, may the gods revive our priceless api
